#!/usr/bin/env bash
#
# build_mesa_xe2.sh
# -----------------
# Builds a modern Mesa (Intel 'iris' OpenGL driver, optionally 'anv' Vulkan) for the
# MRS Apptainer container so that HARDWARE OpenGL works on Intel Lunar Lake / Xe2
# integrated graphics (Arc 130V/140V, PCI 8086:64a0, kernel 'xe' driver).
#
# Generated by Claude.
#
# WHY THIS IS NEEDED
#   The container ships Mesa 21.2.6 (Nov 2021). That predates the Xe2 architecture and
#   the 'xe' kernel driver, so its 'iris' driver does not recognise PCI id 0x64a0 and
#   OpenGL silently falls back to 'llvmpipe' (CPU software rendering) -> slow Gazebo/RViz.
#   Lunar Lake needs Mesa >= 24.2.2. The KERNEL driver is fine (it lives on the host,
#   kernel 6.14, shared into the container); only the container's USERSPACE Mesa is stale.
#
# WHERE TO RUN
#   Inside a WRITABLE + FAKEROOT session of the MRS image (needed for apt + root build).
#   Mesa installs to the bind-mounted $PREFIX (=/opt/mesa), which lives on the HOST, so
#   the result survives after the throwaway build sandbox is deleted. See RUNBOOK below.
#
# TUNABLES (env vars)
#   MESA_VERSION      default 24.2.8   (last of the 24.2 series; safe with focal gcc 9)
#   LIBDRM_VERSION    default 2.4.122  (Mesa 24.2 needs libdrm >= 2.4.119)
#   LLVM_VER          default 18       (matches the libLLVM-18 already in the image)
#   PREFIX            default /opt/mesa (bind this to a host dir so it persists)
#   BUILD_VULKAN      default 0        (1 = also build ANV Vulkan; needs intel-clc, riskier)
#   ENABLE_INTEL_CLC  default auto     (auto|enabled|system)
#   JOBS              default $(nproc)
#
set -euo pipefail

MESA_VERSION="${MESA_VERSION:-24.2.8}"
LIBDRM_VERSION="${LIBDRM_VERSION:-2.4.122}"
SPIRV_TAG="${SPIRV_TAG:-vulkan-sdk-1.3.290.0}"   # SPIRV-Headers/Tools tag (Mesa 24.2 era)
SPIRV_LLVM_BRANCH="${SPIRV_LLVM_BRANCH:-v18.1.1}"  # frozen tag for LLVM 18.1 (NOT the moving llvm_release_180 branch tip)
LLVM_VER="${LLVM_VER:-18}"
PREFIX="${PREFIX:-/opt/mesa}"
BUILD_VULKAN="${BUILD_VULKAN:-0}"
ENABLE_INTEL_CLC="${ENABLE_INTEL_CLC:-auto}"
JOBS="${JOBS:-$(nproc)}"
BUILD_ROOT="${BUILD_ROOT:-/tmp/mesa-build}"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root -- start the container with --fakeroot --writable"

MULTIARCH="lib/x86_64-linux-gnu"
export DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------- 1. build deps
log "Installing build dependencies (apt)"
apt-get update
apt-get install -y --no-install-recommends \
  build-essential pkg-config ca-certificates curl xz-utils git \
  python3-pip python3-setuptools python3-mako \
  flex bison \
  "llvm-${LLVM_VER}-dev" "llvm-${LLVM_VER}-tools" "clang-${LLVM_VER}" \
  "libclang-${LLVM_VER}-dev" "libclc-${LLVM_VER}-dev" \
  libelf-dev libexpat1-dev zlib1g-dev libzstd-dev libpciaccess-dev \
  libx11-dev libx11-xcb-dev libxext-dev libxdamage-dev libxfixes-dev libxrandr-dev \
  libxcb1-dev libxcb-dri3-dev libxcb-dri2-0-dev libxcb-present-dev libxcb-sync-dev \
  libxcb-glx0-dev libxcb-randr0-dev libxcb-shm0-dev libxshmfence-dev libxxf86vm-dev \
  libwayland-dev wayland-protocols libwayland-egl-backend-dev \
  mesa-utils mesa-utils-extra

log "Installing meson + ninja + cmake (focal's apt versions are too old)"
pip3 install --upgrade "meson>=1.4,<1.6" ninja cmake

export PATH="/usr/local/bin:/usr/lib/llvm-${LLVM_VER}/bin:${PATH}"
command -v "llvm-config-${LLVM_VER}" >/dev/null 2>&1 || \
  ln -sf "/usr/lib/llvm-${LLVM_VER}/bin/llvm-config" /usr/local/bin/llvm-config

mkdir -p "$BUILD_ROOT" "$PREFIX"
export PKG_CONFIG_PATH="$PREFIX/$MULTIARCH/pkgconfig:$PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
export LD_LIBRARY_PATH="$PREFIX/$MULTIARCH:${LD_LIBRARY_PATH:-}"

# ---------------------------------------------------------------- 2. libdrm
log "Building libdrm ${LIBDRM_VERSION}"
cd "$BUILD_ROOT"
[ -f "libdrm-${LIBDRM_VERSION}.tar.xz" ] || \
  curl -fLO "https://dri.freedesktop.org/libdrm/libdrm-${LIBDRM_VERSION}.tar.xz"
rm -rf "libdrm-${LIBDRM_VERSION}"; tar xf "libdrm-${LIBDRM_VERSION}.tar.xz"
cd "libdrm-${LIBDRM_VERSION}"
meson setup build --prefix="$PREFIX" --libdir="$MULTIARCH" --buildtype=release \
  -Dintel=enabled -Damdgpu=disabled -Dradeon=disabled -Dnouveau=disabled \
  -Dvmwgfx=disabled -Dvc4=disabled -Dfreedreno=disabled -Detnaviv=disabled -Dtests=false
meson compile -C build -j "$JOBS"
meson install -C build

# ---------------------------------------------------------- 2b. SPIR-V stack
# Mesa's Intel driver needs SPIRV-Tools (ARB_gl_spirv / GL 4.6); focal has no usable
# -dev package, so build SPIRV-Headers + SPIRV-Tools from source into $PREFIX.
log "Building SPIRV-Headers + SPIRV-Tools (${SPIRV_TAG})"
cd "$BUILD_ROOT"
[ -d SPIRV-Headers ] || git clone --depth 1 -b "$SPIRV_TAG" \
  https://github.com/KhronosGroup/SPIRV-Headers.git
cmake -S SPIRV-Headers -B SPIRV-Headers/build \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_BUILD_TYPE=Release
cmake --build SPIRV-Headers/build --target install -j "$JOBS"

[ -d SPIRV-Tools ] || git clone --depth 1 -b "$SPIRV_TAG" \
  https://github.com/KhronosGroup/SPIRV-Tools.git
cmake -S SPIRV-Tools -B SPIRV-Tools/build \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_BUILD_TYPE=Release \
  -DSPIRV_SKIP_TESTS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DSPIRV-Headers_SOURCE_DIR="$BUILD_ROOT/SPIRV-Headers"
cmake --build SPIRV-Tools/build --target install -j "$JOBS"

# SPIRV-LLVM-Translator: provides LLVMSPIRVLib, needed by Mesa's intel-clc on this GPU.
# Not packaged for focal -> build from the branch matching LLVM ${LLVM_VER}.
log "Building SPIRV-LLVM-Translator (${SPIRV_LLVM_BRANCH})"
rm -rf SPIRV-LLVM-Translator   # force fresh checkout of the pinned tag (not a stale clone)
git clone --depth 1 -b "$SPIRV_LLVM_BRANCH" \
  https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git
cmake -S SPIRV-LLVM-Translator -B SPIRV-LLVM-Translator/build \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -DLLVM_DIR="/usr/lib/llvm-${LLVM_VER}/lib/cmake/llvm" \
  -DCMAKE_PREFIX_PATH="$PREFIX" \
  -DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR="$BUILD_ROOT/SPIRV-Headers" \
  -DLLVM_SPIRV_INCLUDE_TESTS=OFF
cmake --build SPIRV-LLVM-Translator/build --target install -j "$JOBS"

# ---------------------------------------------------------------- 3. Mesa
log "Building Mesa ${MESA_VERSION}"
cd "$BUILD_ROOT"
[ -f "mesa-${MESA_VERSION}.tar.xz" ] || \
  curl -fLO "https://archive.mesa3d.org/mesa-${MESA_VERSION}.tar.xz"
rm -rf "mesa-${MESA_VERSION}"; tar xf "mesa-${MESA_VERSION}.tar.xz"
cd "mesa-${MESA_VERSION}"

VULKAN_OPT="-Dvulkan-drivers="
CLC_OPT="-Dintel-clc=auto"        # 'auto' builds intel-clc only if a driver needs it
if [ "$BUILD_VULKAN" = "1" ]; then
  VULKAN_OPT="-Dvulkan-drivers=intel"
  CLC_OPT="-Dintel-clc=enabled"   # ANV needs intel-clc; see SPIRV note in header
fi
case "$ENABLE_INTEL_CLC" in
  enabled) CLC_OPT="-Dintel-clc=enabled";;
  system)  CLC_OPT="-Dintel-clc=system";;
  auto)    CLC_OPT="-Dintel-clc=auto";;
esac

meson setup build --prefix="$PREFIX" --libdir="$MULTIARCH" --buildtype=release \
  -Dgallium-drivers=iris,swrast \
  "$VULKAN_OPT" "$CLC_OPT" \
  -Dplatforms=x11 \
  -Dglx=dri -Ddri3=enabled -Degl=enabled -Dgbm=enabled \
  -Dopengl=true -Dgles1=disabled -Dgles2=enabled \
  -Dllvm=enabled -Dshared-llvm=enabled \
  -Dvalgrind=disabled -Dlibunwind=disabled -Dvideo-codecs=
meson compile -C build -j "$JOBS"
meson install -C build

# ---------------------------------------------------------------- 4. done
cat <<EOF

$(log "SUCCESS -- Mesa ${MESA_VERSION} installed to ${PREFIX}")

To VERIFY hardware acceleration (run in a session with /dev/dri bound; headless EGL,
no X needed):

  LD_LIBRARY_PATH=${PREFIX}/${MULTIARCH}:\$LD_LIBRARY_PATH \\
  LIBGL_DRIVERS_PATH=${PREFIX}/${MULTIARCH}/dri \\
  __EGL_VENDOR_LIBRARY_DIRS=${PREFIX}/share/glvnd/egl_vendor.d \\
  eglinfo -B 2>/dev/null | grep -iE "device|renderer|vendor"

Expect an Intel 'Arc Graphics' renderer via the 'iris' driver -- NOT 'llvmpipe'.
For GLX/X apps use the same three env vars plus __GLX_VENDOR_LIBRARY_NAME=mesa and run
'glxinfo -B'.
EOF
